openapi: "3.0.3"
info:
  title: C-3-2 ヒヤリハット管理システムAPI
  version: "0.0.1"
servers:
  - url: https://api.server.test/v1
paths:
  /nearmissinfolist:
    $ref: "./paths/nearMissInfoList.yaml"
  /categorylist:
    $ref: "./paths/categoryList.yaml"
  /attributes:
    $ref: "./paths/attributes.yaml"
  # /{targetDataModel}:
  #   $ref: "./paths/targetDataModel.yaml"
  /login:
    $ref: "./paths/login.yaml"
components:
  schemas:
    authentication.Information:
      $ref: "./components/schemas/authentication/information.yaml#/information"
    authentication.Token:
      $ref: "./components/schemas/authentication/token.yaml#/token"
    dataModel.attributes:
      $ref: "./components/schemas/dataModel/attributes.yaml#/attributes"
    dataModel.nearMissInfoList:
      $ref: "./components/schemas/dataModel/nearMissInfoList.yaml#/nearMissInfoList"
    dataModel.categoryList:
      $ref: "./components/schemas/dataModel/categoryList.yaml#/categoryList"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apiKey
      in: header
    Authorization:
      type: http
      scheme: bearer
      description: アクセストークン発行APIで発行したアクセストークン
